
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BREAK CIN COMA COMENT CORCHETES COUT DO DOBLER ELSE ENDL EXPBOOL FALSE FLOAT ID IF IGUALES INCLUDE INT IOSTREAM LLAVES LTGT MICHI NAMESPACE NUM NUMERO OPBIN OPERACIONES OPUNA PARENA PARENC PARENTESIS PUNTOYCOMA RETURN STD STRING TRUE USING WHILEroot : inicioinicio : instruccion inicioinicio : epsilonepsilon : opestring : STRING programa : MICHI INCLUDE DOBLER IOSTREAM DOBLER USING NAMESPACE STD PUNTOYCOMA bloquebloque : basico ID PARENTESIS PARENTESIS LLAVES decls mostrarvarios condicion RETURN NUMERO PUNTOYCOMA LLAVES mostrarvarios : mostrarvarios mostrar\n                      | mostrarvarios mostrardatos\n\t                  | epsilon  mostrardatos : COUT DOBLER ID DOBLER ENDL PUNTOYCOMA mostrar : COUT DOBLER opestring DOBLER ENDL PUNTOYCOMA condicionif : IF PARENTESIS ID DOBLER NUMERO PARENTESIS LLAVES decls mostrarvarios LLAVEScondicionelse : ELSE LLAVES decls mostrarvarios LLAVES condicion : condicionif\n\t             | condicionelse \n    decls : decls decljuntos\n          | epsilon\n\n    decljuntos : decl\n\t              | decl2 \n\t\t\t\t  | operaciones \n    decl2 : tipo ID PUNTOYCOMA\n\t\n    \n    decl : tipo ID IGUALES NUMERO PUNTOYCOMA\n\t\n     operaciones : tipo ID IGUALES operacion PUNTOYCOMA  operacion : ID OPERACIONES ID \n    tipo : basico\n\n    \n    basico : INT\n           | FLOAT\n\t instruccion : programa '
    
_lr_action_items = {'$end':([0,1,2,3,4,5,7,16,66,],[-4,0,-1,-4,-3,-29,-2,-6,-7,]),'MICHI':([0,3,5,16,66,],[6,6,-29,-6,-7,]),'INCLUDE':([6,],[8,]),'DOBLER':([8,10,39,50,51,52,53,],[9,11,44,59,60,-5,61,]),'IOSTREAM':([9,],[10,]),'USING':([11,],[12,]),'NAMESPACE':([12,],[13,]),'STD':([13,],[14,]),'PUNTOYCOMA':([14,42,49,56,57,67,68,71,],[15,48,58,64,65,72,73,-25,]),'INT':([15,23,24,25,28,30,31,32,46,48,54,64,65,75,76,],[18,-4,18,-18,-17,-19,-20,-21,-4,-22,18,-23,-24,-4,18,]),'FLOAT':([15,23,24,25,28,30,31,32,46,48,54,64,65,75,76,],[19,-4,19,-18,-17,-19,-20,-21,-4,-22,19,-23,-24,-4,19,]),'ID':([17,18,19,26,33,44,45,47,63,],[20,-27,-28,-26,42,51,53,55,71,]),'PARENTESIS':([20,21,40,69,],[21,22,45,74,]),'LLAVES':([22,25,28,29,30,31,32,35,36,41,46,48,54,58,62,64,65,72,73,74,75,76,77,],[23,-18,-17,-10,-19,-20,-21,-8,-9,46,-4,-22,-4,66,70,-23,-24,-12,-11,75,-4,-4,78,]),'COUT':([23,24,25,27,28,29,30,31,32,35,36,46,48,54,62,64,65,72,73,75,76,77,],[-4,-4,-18,39,-17,-10,-19,-20,-21,-8,-9,-4,-22,-4,39,-23,-24,-12,-11,-4,-4,39,]),'IF':([23,24,25,27,28,29,30,31,32,35,36,48,64,65,72,73,],[-4,-4,-18,40,-17,-10,-19,-20,-21,-8,-9,-22,-23,-24,-12,-11,]),'ELSE':([23,24,25,27,28,29,30,31,32,35,36,48,64,65,72,73,],[-4,-4,-18,41,-17,-10,-19,-20,-21,-8,-9,-22,-23,-24,-12,-11,]),'RETURN':([34,37,38,70,78,],[43,-15,-16,-14,-13,]),'IGUALES':([42,],[47,]),'NUMERO':([43,47,61,],[49,56,69,]),'STRING':([44,],[52,]),'OPERACIONES':([55,],[63,]),'ENDL':([59,60,],[67,68,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'root':([0,],[1,]),'inicio':([0,3,],[2,7,]),'instruccion':([0,3,],[3,3,]),'epsilon':([0,3,23,24,46,54,75,76,],[4,4,25,29,25,29,25,29,]),'programa':([0,3,],[5,5,]),'bloque':([15,],[16,]),'basico':([15,24,54,76,],[17,26,26,26,]),'decls':([23,46,75,],[24,54,76,]),'mostrarvarios':([24,54,76,],[27,62,77,]),'decljuntos':([24,54,76,],[28,28,28,]),'decl':([24,54,76,],[30,30,30,]),'decl2':([24,54,76,],[31,31,31,]),'operaciones':([24,54,76,],[32,32,32,]),'tipo':([24,54,76,],[33,33,33,]),'condicion':([27,],[34,]),'mostrar':([27,62,77,],[35,35,35,]),'mostrardatos':([27,62,77,],[36,36,36,]),'condicionif':([27,],[37,]),'condicionelse':([27,],[38,]),'opestring':([44,],[50,]),'operacion':([47,],[57,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root","S'",1,None,None,None),
  ('root -> inicio','root',1,'p_root','Traductor.py',117),
  ('inicio -> instruccion inicio','inicio',2,'p_inicio','Traductor.py',123),
  ('inicio -> epsilon','inicio',1,'p_inicio2','Traductor.py',127),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','Traductor.py',131),
  ('opestring -> STRING','opestring',1,'p_opestring','Traductor.py',135),
  ('programa -> MICHI INCLUDE DOBLER IOSTREAM DOBLER USING NAMESPACE STD PUNTOYCOMA bloque','programa',10,'p_programa','Traductor.py',139),
  ('bloque -> basico ID PARENTESIS PARENTESIS LLAVES decls mostrarvarios condicion RETURN NUMERO PUNTOYCOMA LLAVES','bloque',12,'p_bloque','Traductor.py',143),
  ('mostrarvarios -> mostrarvarios mostrar','mostrarvarios',2,'p_mostrarvarios','Traductor.py',147),
  ('mostrarvarios -> mostrarvarios mostrardatos','mostrarvarios',2,'p_mostrarvarios','Traductor.py',148),
  ('mostrarvarios -> epsilon','mostrarvarios',1,'p_mostrarvarios','Traductor.py',149),
  ('mostrardatos -> COUT DOBLER ID DOBLER ENDL PUNTOYCOMA','mostrardatos',6,'p_mostrardatos','Traductor.py',156),
  ('mostrar -> COUT DOBLER opestring DOBLER ENDL PUNTOYCOMA','mostrar',6,'p_mostrar','Traductor.py',160),
  ('condicionif -> IF PARENTESIS ID DOBLER NUMERO PARENTESIS LLAVES decls mostrarvarios LLAVES','condicionif',10,'p_condicionif','Traductor.py',164),
  ('condicionelse -> ELSE LLAVES decls mostrarvarios LLAVES','condicionelse',5,'p_condicionelse','Traductor.py',168),
  ('condicion -> condicionif','condicion',1,'p_condicion','Traductor.py',172),
  ('condicion -> condicionelse','condicion',1,'p_condicion','Traductor.py',173),
  ('decls -> decls decljuntos','decls',2,'p_decls','Traductor.py',178),
  ('decls -> epsilon','decls',1,'p_decls','Traductor.py',179),
  ('decljuntos -> decl','decljuntos',1,'p_decljuntos','Traductor.py',188),
  ('decljuntos -> decl2','decljuntos',1,'p_decljuntos','Traductor.py',189),
  ('decljuntos -> operaciones','decljuntos',1,'p_decljuntos','Traductor.py',190),
  ('decl2 -> tipo ID PUNTOYCOMA','decl2',3,'p_decl2','Traductor.py',195),
  ('decl -> tipo ID IGUALES NUMERO PUNTOYCOMA','decl',5,'p_decl','Traductor.py',202),
  ('operaciones -> tipo ID IGUALES operacion PUNTOYCOMA','operaciones',5,'p_operaciones','Traductor.py',208),
  ('operacion -> ID OPERACIONES ID','operacion',3,'p_operacion','Traductor.py',212),
  ('tipo -> basico','tipo',1,'p_tipo','Traductor.py',217),
  ('basico -> INT','basico',1,'p_basico','Traductor.py',224),
  ('basico -> FLOAT','basico',1,'p_basico','Traductor.py',225),
  ('instruccion -> programa','instruccion',1,'p_instruccion','Traductor.py',230),
]
